## Four covariate constructions, one estimator, one dataset each.
##
##   marginal   integrate the MOMENTS over the covariate distribution, score once
##   gh         sum_k w_k * NLL(obs, pred at a_k),  Gauss-Hermite nodes
##   gl         the same, Gauss-Legendre over a truncated normal
##   taylor     the same, with the 2nd-order (Laplace) stencil as its weights
##
## This is the comparison the pure-R scripts made analytically
## (covariate-threeway.R), now through the real package: real rxode2 solves, the
## real -2LL, the real analytic gradients, the real optimiser. Everything except
## `cov_method` is held fixed, so a difference in the answer is a difference in
## the objective and nothing else.
##
## THREE populations with differing covariate means AND spreads. One population
## does not identify the coefficient at all -- the likelihood is exactly flat
## along tcl' = tcl + (b-b')*mu_a, omega'^2 = omega^2 + (b^2-b'^2)*sd_a^2 -- so a
## single-population comparison measures where the optimiser stopped, nothing
## more. See covariate-matched-conditional.R.
##
## Run:  Rscript validation/covariate-method-comparison.R
suppressMessages({library(rxode2); library(nloptr)})
suppressMessages(devtools::load_all(".", quiet = TRUE))
kv <- function(k, v) cat(sprintf("%s\t%s\n", k, paste(v, collapse = ",")))

TCL <- log(1); TV <- log(10); TCOV <- 0.75; OM <- 0.30; ADD <- 0.30
TT   <- c(0.5, 1, 1.5, 2, 3, 4, 5, 6, 8)
EV   <- rxode2::et(amt = 100)
POPS <- list(p1 = c(mu = -0.45, sd = 0.30),
             p2 = c(mu =  0.00, sd = 0.55),
             p3 = c(mu =  0.50, sd = 0.35))
NSUB <- 100L

truth <- function() {
  ini({tcl <- log(1); tv <- log(10); tcov <- 0.75; add.err <- 0.3
       eta.cl ~ 0.09})
  model({cl <- exp(tcl + tcov * AAA + eta.cl); v <- exp(tv)
         d/dt(centr) <- -cl / v * centr; cp <- centr / v
         cp ~ add(add.err)})
}
fitmod <- function() {
  ini({tcl <- log(1.4); tv <- log(11); tcov <- 0.40; add.err <- 0.35
       eta.cl ~ 0.16})
  model({cl <- exp(tcl + tcov * AAA + eta.cl); v <- exp(tv)
         d/dt(centr) <- -cl / v * centr; cp <- centr / v
         cp ~ add(add.err)})
}

## ---- data: ONE aggregate (E, V) per population, marginal over its covariates
## Generated by simulating SUBJECTS -- each with its own covariate draw and its
## own eta -- and reducing to (E, V, n). That is what a published study reports,
## and it is an independent construction from the quadrature every estimator
## below uses to predict.
gen <- datagen(
  setNames(lapply(POPS, function(p)
    list(model = truth, times = TT, ev = EV, n = NSUB,
         cov_dist = list(AAA = list(mu = p[["mu"]], sd = p[["sd"]])))),
    names(POPS)),
  control = datagenControl(n_sim = 200000L, seed = 20260813L))
kv("data_studies", paste(names(gen), collapse = ","))
kv("data_E_p2", sprintf("%.4f", gen$p2$E))

set_method <- function(g, m, ctl = list())
  lapply(g, function(s) { s$cov_method <- m; s$cov_control <- ctl; s })

METHODS <- list(marginal = list(),
                gh       = list(n_nodes = 9L),
                gl       = list(n_nodes = 9L),
                taylor   = list(order = 2L))

## ---- 1. gradient check: is the analytic gradient right on a node objective? --
## A node study is an ordinary fixed-covariate study whose combination
## coefficient rides in `n`, and `n` is a linear multiplier on the -2LL -- so the
## analytic gradient should be exact, not approximately right. Checked away from
## the optimum, where every component is large (at truth they are all ~0 and any
## gradient passes).
ui    <- suppressMessages(rxode2::rxode2(fitmod))
ovar  <- admixr2:::.admOutputVar(ui)
gcheck <- function(m, ctl) {
  ctl_g <- adghControl(studies = set_method(gen, m, ctl), grad = "analytical",
                       n_nodes = 7L, print = 0L, covMethod = "none")
  pinfo <- admixr2:::.admDriverPinfo(ui, ctl_g)
  u     <- admixr2:::.admDriverUnits(ctl_g$studies, ui, ovar)$studies
  u     <- admixr2:::.admCovExpandNodes(u)
  u     <- admixr2:::.admCheckCovariates(ui, pinfo, u, "analytical", "adgh")
  rx    <- admixr2:::.admLoadModel(ui)
  sm    <- tryCatch(admixr2:::.admLoadSensModel(ui), error = function(e) NULL)
  grid  <- admixr2:::.adghNodeGrid(7L, pinfo$n_eta)
  p     <- admixr2:::.admBuildOptVec(pinfo)$p0
  f     <- function(pp) admixr2:::.adghNLL(pp, pinfo, u, rx, ovar, grid, 1L)
  ga    <- admixr2:::.adghGrad(p, pinfo, u, sm, rx, ovar, grid, 1L, 1e-4)
  h     <- 1e-5
  gfd   <- vapply(seq_along(p), function(j) {
    pp <- p; pm <- p; pp[j] <- pp[j] + h; pm[j] <- pm[j] - h
    (f(pp) - f(pm)) / (2 * h)
  }, numeric(1))
  kv(sprintf("grad_%s", m),
     sprintf("n_units=%d nll=%.4f max|g|=%.2f max_rel_err=%.2e",
             length(u), f(p), max(abs(ga)),
             max(abs(ga - gfd)) / max(abs(gfd))))
}
for (m in names(METHODS)) gcheck(m, METHODS[[m]])

## ---- 2. the comparison: fit each, report where tcov lands -------------------
res <- list()
for (m in names(METHODS)) {
  t0 <- Sys.time()
  fit <- tryCatch(
    suppressWarnings(suppressMessages(nlmixr2est::nlmixr2(
      fitmod, admData(), est = "adgh",
      control = adghControl(studies = set_method(gen, m, METHODS[[m]]),
                            grad = "analytical", n_nodes = 7L,
                            maxeval = 400L, print = 0L, covMethod = "none")))),
    error = function(e) e)
  dt <- as.numeric(difftime(Sys.time(), t0, units = "secs"))
  if (inherits(fit, "error")) { kv(sprintf("fit_%s_ERROR", m), conditionMessage(fit)); next }
  ax <- fit$env$admExtra
  res[[m]] <- c(tcl = unname(ax$struct[["tcl"]]), tv = unname(ax$struct[["tv"]]),
                tcov = unname(ax$struct[["tcov"]]),
                add.err = unname(sqrt(ax$sigma_var[[1]])),
                om = unname(sqrt(ax$omega[1, 1])),
                obj = fit$objective, secs = dt)
  kv(sprintf("fit_%s", m),
     sprintf("tcov=%.4f tcl=%.4f tv=%.4f add=%.4f om=%.4f obj=%.3f %.0fs",
             res[[m]][["tcov"]], res[[m]][["tcl"]], res[[m]][["tv"]],
             res[[m]][["add.err"]], res[[m]][["om"]], res[[m]][["obj"]], dt))
}

cat("\n")
cat(sprintf("%-10s %9s %9s %9s %9s %9s %8s\n",
            "method", "tcov", "bias", "tcl", "om", "add.err", "secs"))
cat(sprintf("%-10s %9.4f %9s %9.4f %9.4f %9.4f %8s\n",
            "TRUTH", TCOV, "", TCL, OM, ADD, ""))
for (m in names(res)) {
  r <- res[[m]]
  cat(sprintf("%-10s %9.4f %+9.4f %9.4f %9.4f %9.4f %8.0f\n",
              m, r[["tcov"]], r[["tcov"]] - TCOV, r[["tcl"]], r[["om"]],
              r[["add.err"]], r[["secs"]]))
}
cat("\nObjectives are NOT comparable across methods -- they are different\n",
    "functionals of the same data, not different approximations of one.\n", sep = "")
