## ============================================================================
## Panel A: observed vs predicted per study -- own model, cross model, MBMA
## ============================================================================
##
##   Rscript validation/page-abstract-panelA.R
##
## For each study, three predicted concentration-time profiles over its own
## dosing design:
##
##   Original   that study's OWN published model
##   Cross      the OTHER study's published model, applied to this design
##   MBMA       the unifying model admixr2 fitted across BOTH studies
##
## with the study's observed aggregate data (mean +/- SD) as black point-ranges.
## The point of the panel: "Cross" is what you get by borrowing a model built on
## a different design, and "MBMA" is what you get by combining the evidence.
##
## Everything here is marginal over the study's WEIGHT DISTRIBUTION, matching
## what admixr2 actually fitted -- the original panel predicts at the study mean
## weight instead, so the ribbons are not directly comparable in width.
## Ribbons and observed bars both INCLUDE proportional residual error.

## load_all, NOT library(admixr2): the covariate work lives in this worktree and
## the installed package does not have it -- library() here fails with
## "the following parameter(s) are required for solving: WT".
suppressMessages({library(rxode2); library(ggplot2)})
suppressMessages(devtools::load_all(".", quiet = TRUE))
set.seed(1)

N_SIM <- 800L
ln_from <- function(mu, sd)
  list(meanlog = log(mu^2 / sqrt(sd^2 + mu^2)), sdlog = sqrt(log(1 + sd^2 / mu^2)))
WT_ISS <- ln_from(20.2, 9.2); WT_ALS <- ln_from(18.1, 8.5)

## ---- designs ---------------------------------------------------------------
DES <- list(
  Ayuthaya = list(ev = rxode2::et(amt = 17.5, dur = 1),
                  tgrid = seq(0.05, 6, by = 0.05),
                  obs_t = c(0.5, 1, 1.25, 1.5, 2, 3, 4, 5, 6),
                  n = 14L, wt = WT_ISS),
  Alsultan = list(ev = rxode2::et(amt = 15, ii = 6, addl = 4, dur = 2),
                  tgrid = seq(18, 24, by = 0.05),
                  obs_t = c(21, 23.5),
                  n = 72L, wt = WT_ALS))

## ---- the three parameter sets ----------------------------------------------
P_ISS <- list(two = TRUE,  prop = 0.12,
              th = c(lcl = log(0.16), lvc = log(3.86), lvp = log(0.19),
                     lq = log(0.13), clwt = 0.97, vpwt = 1.07, qwt = 1.19),
              om = c(sqrt(0.062), sqrt(0.048)))
P_ALS <- list(two = FALSE, prop = 0.119,
              th = c(lcl = log(2.99), lv = log(9.55)),
              om = c(sqrt(0.0223), sqrt(0.0134)))
P_MBMA <- list(two = TRUE, prop = 0.1085,
               th = c(lcl = -1.6655, lvc = 1.0203, lvp = -1.3883, lq = -3.8081,
                      clwt = 0.8746, vpwt = 0.9505, qwt = 1.8737),
               om = c(0.1517, 0.4656))

m2c <- rxode2::rxode2({
  cl <- exp(lcl + eta.cl) * WT^clwt
  vc <- exp(lvc + eta.vc)
  vp <- exp(lvp) * WT^vpwt
  q  <- exp(lq)  * WT^qwt
  f(centr)    <- WT
  d/dt(centr) <- -(cl + q) / vc * centr + q / vp * peri
  d/dt(peri)  <-        q  / vc * centr - q / vp * peri
  cp <- centr / vc
})
m1c <- rxode2::rxode2({
  cl <- exp(lcl + eta.cl) * (WT / 20)
  v  <- exp(lv  + eta.v)  * (WT / 20)
  f(centr)    <- WT
  d/dt(centr) <- -cl / v * centr
  cp <- centr / v
})

## marginal mean and SD over (weight, random effects), residual included
profile_of <- function(P, des, times) {
  u  <- (seq_len(N_SIM) - 0.5) / N_SIM
  z1 <- qnorm(u)
  z2 <- qnorm((u + 0.5) %% 1)                    # decorrelated second dimension
  wt <- qlnorm(rev(u), des$wt$meanlog, des$wt$sdlog)
  pars <- if (P$two)
    data.frame(t(P$th), eta.cl = P$om[1] * z1, eta.vc = P$om[2] * z2, WT = wt)
  else
    data.frame(t(P$th), eta.cl = P$om[1] * z1, eta.v  = P$om[2] * z2, WT = wt)
  ev <- des$ev |> rxode2::et(times)
  out <- rxode2::rxSolve(if (P$two) m2c else m1c, params = pars, events = ev,
                         cores = 1L, nDisplayProgress = .Machine$integer.max)
  keep <- out[["time"]] %in% times
  cpm  <- matrix(out[["cp"]][keep], nrow = N_SIM, byrow = TRUE)
  mu   <- colMeans(cpm)
  v    <- apply(cpm, 2L, var) + P$prop^2 * mu^2   # + proportional residual
  data.frame(time = times, mean = mu, sd = sqrt(pmax(v, 0)))
}

cat("simulating profiles ...\n")
df_pred <- do.call(rbind, lapply(names(DES), function(sn) {
  d <- DES[[sn]]
  own   <- if (sn == "Ayuthaya") P_ISS  else P_ALS
  cross <- if (sn == "Ayuthaya") P_ALS  else P_ISS
  rbind(cbind(profile_of(own,   d, d$tgrid), model = "Original", study = sn),
        cbind(profile_of(cross, d, d$tgrid), model = "Cross",    study = sn),
        cbind(profile_of(P_MBMA, d, d$tgrid), model = "MBMA",    study = sn))
}))
df_pred$model <- factor(df_pred$model, levels = c("Original", "Cross", "MBMA"))

## ---- observed aggregate data, generated by admixr2 -------------------------
cat("generating observed aggregate data ...\n")
mod_iss <- function() {
  ini({lcl <- log(0.16); lvc <- log(3.86); lvp <- log(0.19); lq <- log(0.13)
       clwt <- 0.97; vpwt <- 1.07; qwt <- 1.19
       eta.cl ~ 0.062; eta.vc ~ 0.048; prop.err <- 0.12})
  model({cl <- exp(lcl + eta.cl) * WT^clwt; vc <- exp(lvc + eta.vc)
         vp <- exp(lvp) * WT^vpwt; q <- exp(lq) * WT^qwt
         f(centr) <- WT
         d/dt(centr) <- -(cl + q)/vc*centr + q/vp*peri
         d/dt(peri)  <-        q /vc*centr - q/vp*peri
         cp <- centr/vc; cp ~ prop(prop.err)})
}
mod_als <- function() {
  ini({lcl <- log(2.99); lv <- log(9.55)
       eta.cl ~ 0.0223; eta.v ~ 0.0134; prop.err <- 0.119})
  model({cl <- exp(lcl + eta.cl) * (WT/20); v <- exp(lv + eta.v) * (WT/20)
         f(centr) <- WT
         d/dt(centr) <- -cl/v*centr; cp <- centr/v; cp ~ prop(prop.err)})
}
gen <- datagen(list(
  Ayuthaya = list(model = mod_iss, times = DES$Ayuthaya$obs_t,
                  ev = DES$Ayuthaya$ev, n = 14L, cov_dist = list(WT = WT_ISS)),
  Alsultan = list(model = mod_als, times = DES$Alsultan$obs_t,
                  ev = DES$Alsultan$ev, n = 72L, cov_dist = list(WT = WT_ALS))),
  control = datagenControl(n_sim = 30000L, seed = 12345L))

df_obs <- do.call(rbind, lapply(names(gen), function(sn) {
  g <- gen[[sn]]
  data.frame(study = sn, time = g$times, mean = as.numeric(g$E),
             sd = sqrt(pmax(diag(g$V), 0)))
}))
df_obs$lo <- df_obs$mean - df_obs$sd; df_obs$hi <- df_obs$mean + df_obs$sd

cols <- c(Original = "#E69F00", Cross = "#56B4E9", MBMA = "#1B7837")
p <- ggplot() +
  geom_ribbon(data = df_pred,
              aes(x = time, ymin = mean - sd, ymax = mean + sd, fill = model),
              alpha = 0.15, colour = NA) +
  geom_line(data = df_pred, aes(x = time, y = mean, colour = model),
            linewidth = 0.9) +
  geom_pointrange(data = df_obs, aes(x = time, y = mean, ymin = lo, ymax = hi),
                  colour = "black", size = 0.3, linewidth = 0.6) +
  facet_wrap(~study, scales = "free", nrow = 1) +
  scale_colour_manual(values = cols, name = NULL) +
  scale_fill_manual(values = cols, name = NULL) +
  labs(x = "Time (h)", y = "Vancomycin (mg/L)",
       subtitle = paste("Marginal over each study's weight distribution;",
                        "ribbons and bars include proportional residual")) +
  theme_bw(base_size = 14) +
  theme(panel.grid.minor = element_blank(),
        strip.background = element_rect(fill = "grey92"),
        strip.text = element_text(size = 12, face = "bold"),
        legend.position = "bottom",
        plot.subtitle = element_text(size = 8, colour = "grey40"))

out <- file.path(Sys.getenv("ADM_FIG_DIR", "."), "page-panelA.png")
ggsave(out, p, width = 11, height = 5, dpi = 150)
cat("wrote", normalizePath(out), "\n\n")

## how well does each model describe each study's observed means?
cat("Root mean squared relative deviation from the observed means:\n")
for (sn in names(DES)) {
  ot <- DES[[sn]]$obs_t
  ob <- df_obs[df_obs$study == sn, ]
  for (m in levels(df_pred$model)) {
    pr <- df_pred[df_pred$study == sn & df_pred$model == m, ]
    fit <- approx(pr$time, pr$mean, xout = ot)$y
    cat(sprintf("  %-9s %-9s %6.1f%%\n", sn, m,
                100 * sqrt(mean((fit / ob$mean - 1)^2))))
  }
}
